name = "video-bandwidth-worker"
main = "src/index.ts"
compatibility_date = "2024-05-16"

[vars]
# ENVIRONMENT_SECRET should be set via: wrangler secret put ENVIRONMENT_SECRET

[[kv_namespaces]]
binding = "VIDEO_KEYS"
id = "53f90cdadb5f4286ad2231888f19e9e6"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vid" # TODO: Update with your private R2 bucket name

[[analytics_engine_datasets]]
binding = "WAE"
dataset = "video_bandwidth"
